### ISSUE TITLE
can't execute PyPop 0.7.0 with example files after installation

### ISSUE THREAD

**Issue by emmastyl** [alexlancaster/pypop#55]
Hi there!

I am using Ubuntu 20 04 and i have installed PyPop v. 0.7.0. 
I execute PyPop with the example files given using the following 2 commands below  

```
./python-batch -c sample.ini sample.pop
```
and 

```
./popmeta-batch -c sample.ini sample.pop
```
and i get the following message:

Traceback (most recent call last):
  File "<string>", line 38, in <module>
  File "/home/alex/src/python-installer/iu.py", line 277, in importHook
  File "/home/alex/src/python-installer/iu.py", line 362, in doimport
  File "/home/alex/ihwg/src/buildstandalone/out5.pyz/Meta", line 46, in <module>
  File "/home/alex/src/python-installer/iu.py", line 277, in importHook
  File "/home/alex/src/python-installer/iu.py", line 362, in doimport
  File "/home/alex/ihwg/src/buildstandalone/out5.pyz/libxslt", line 52, in <module>
  File "/home/alex/src/python-installer/iu.py", line 277, in importHook
  File "/home/alex/src/python-installer/iu.py", line 347, in doimport
  File "/home/alex/src/python-installer/iu.py", line 184, in getmod
  File "/home/alex/src/python-installer/iu.py", line 46, in getmod
ImportError: libgcrypt.so.11: cannot open shared object file: No such file or directory

What is your suggestion?

Thanks in advance

**Comment by jingydz** [comment]
$ ./pypop
PyPop: Python for Population Genetics (0.7.0)
Copyright (C) 2003-2005 Regents of the University of California
This is free software.  There is NO warranty; not even for
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

You may redistribute copies of PyPop under the terms of the
GNU General Public License.  For more information about these
matters, see the file named COPYING.

To accept the default in brackets for each filename, simply press
return for each prompt.

Please enter config filename [config.ini]: sample.ini
Please enter population filename [no default]: sample.pop
PyPop is processing sample.pop ...
LOG: Data file has no header data block
LOG: estimating all pairwise LD: with no permutation test
Traceback (most recent call last):
  File "<string>", line 335, in <module>
  File "/home/alex/ihwg/src/buildstandalone/out1.pyz/Main", line 435, in __init__
  File "/home/alex/ihwg/src/buildstandalone/out1.pyz/Main", line 1173, in _genTextOutput
  File "/home/alex/src/python-installer/iu.py", line 277, in importHook
  File "/home/alex/src/python-installer/iu.py", line 362, in doimport
  File "/home/alex/ihwg/src/buildstandalone/out1.pyz/libxslt", line 52, in <module>
  File "/home/alex/src/python-installer/iu.py", line 277, in importHook
  File "/home/alex/src/python-installer/iu.py", line 347, in doimport
  File "/home/alex/src/python-installer/iu.py", line 184, in getmod
  File "/home/alex/src/python-installer/iu.py", line 46, in getmod
ImportError: libgcrypt.so.11: cannot open shared object file: No such file or directory

Hi, the message that I get is same as yours.

**Comment by chagas98** [comment]
Hello, 

After two days of troubleshooting, I tried to fix this issue by downloading the libgcrypt.so.11 file separately and copy to the bin folder. Download the i389 format from here: https://brbsix.github.io/2015/10/29/fix-missing-libgcrypt11-for-brackets-text-editor/ 

I ran with sample.ini and sample.pop files and it worked.

**Comment by alexlancaster** [comment]
> Hello @emmastyl @jingydz,
> 
> After two days of troubleshooting, I tried to fix this issue by downloading the libgcrypt.so.11 file separately and copy to the bin folder. Download the i389 format from here: https://brbsix.github.io/2015/10/29/fix-missing-libgcrypt11-for-brackets-text-editor/
> 
> I ran with sample.ini and sample.pop files and it worked.

Thanks for the update and the workaround @chagas98 .  The current binaries are getting very long in the tooth.  I hope to upgrade the whole thing to Python 3.x and get this up on PyPi soon (no promises as to when).
